### ISSUE TITLE
POM dependency generation shall support type and scope

### ISSUE THREAD

**Issue by chrisdoyle** [chrisdoyle/gradle-fury#21]
Oh, Gradle...

The POM generation task shall accurately capture both `<scope />` and `<classifier />` values in the `<dependency />` declarations.  I found a rather disheartening post related to the subject:

https://discuss.gradle.org/t/maven-publish-plugin-generated-pom-making-dependency-scope-runtime/7494

This ticket is an attempt to "Use the 'pom.withXml' hook to fix the dependency scopes as needed" method as a "solution", as proposed in Mr. Niederwieser's response.  Sigh.

**Comment by spyhunter99** [comment]
Source material
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Dependency.html

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

We also need to add to the readme and/or wiki limitations of the pom dependency mechanism, since gradle is the wild wild west, it supports more shenanigans that maven, especially with local file dependencies (libs folder)

**Comment by spyhunter99** [comment]
#46 related
